pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: true
    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    customCommand: run build
    verbose: true

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

    includeRootFolder: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
